---
install_core: true
install_dev: true

user_home: "{{ lookup('env', 'HOME') }}"

core_packages:
  - curl                                 # Загрузка файлов по HTTP/HTTPS (командная строка)
  - wget                                 # Альтернатива curl для загрузки файлов
  - git                                  # Система контроля версий
  - build-essential                      # Базовый набор для компиляции ПО в Debian/Ubuntu
  - software-properties-common           # Управление репозиториями APT
  - apt-transport-https                  # Поддержка HTTPS в APT
  - ca-certificates                      # Сертификаты доверенных центров сертификации
  - gnupg                                # Шифрование и подписи (GPG)
  - lsb-release                          # Информация о дистрибутиве Linux
  - unzip                                # Распаковка ZIP-архивов
  - zip                                  # Создание ZIP-архивов
  - btop                                 # Современный монитор ресурсов с графиками
  - ncdu                                 # Анализ использования диска (в терминале)
  - nethogs                              # Мониторинг сетевого трафика по процессам
  - tree                                 # Вывод структуры директорий в виде дерева
  - fzf                                  # Fuzzy-поиск по файлам и командам
  - ripgrep                              # Быстрый поиск текста в файлах (аналог grep)
  - bat                                  # Улучшенный cat с подсветкой синтаксиса
  - fd-find                              # Быстрый аналог find для поиска файлов
  - jq                                   # Обработка JSON в командной строке
  - yq                                   # Обработка YAML/JSON в командной строке
  - tmux                                 # Мультиплексор терминалов (разделение экрана, сессии)
  - mtr                                  # Мониторинг сети (аналог traceroute)
  - tcpdump                              # Сбор трафика сети
  - wireshark                            # Сбор трафика сети (аналог tcpdump)
  - nmap                                 # Сканер сети


dev_packages:
  - postgresql-client                    # Клиент PostgreSQL
  - redis-tools                          # Утилиты для Redis
  - openjdk-17-jdk                       # JDK 17
  - maven                                # Средство сборки и развертывания Java-приложений
  - pipx                                 # Установка и использование пакетов Python в виртуальной среде
