---
# Главный плейбук для настройки рабочего окружения разработчика

- hosts: localhost
  connection: local
  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: ~/.local/bin существует
      file:
        path: "{{ user_home }}/.local/bin"
        state: directory
        mode: '0755'
      tags: always

  roles:
    - role: core
      when: install_core | bool
      tags: core

    - role: dev
      when: install_dev_env | bool
      tags: dev