---

- hosts: localhost
  connection: local
  vars_files:
    - group_vars/all.yml

  roles:
    - role: core
      when: install_core | bool
      tags: core

    - role: dev
      when: install_dev_env | bool
      tags: dev
