---
# Настройка VS Code

- name: Проверка наличия VS Code
  command: which code
  register: code_check
  ignore_errors: true
  tags: ide

- name: Настройка VS Code (если установлен)
  when: code_check.rc == 0
  block:
    - name: Установка расширений VS Code
      command: code --install-extension {{ item }} --force --no-sandbox --user-data-dir "{{ target_user_home }}/.config/Code/User"
      loop: "{{ vscode_extensions }}"
      become: true
      become_user: "{{ username }}"
      environment:
        HOME: "{{ target_user_home }}"
      tags: ide

    - name: Настройка конфигурации VS Code
      copy:
        content: |
          {
            "editor.renderWhitespace": "all",
            "files.autoSave": "onFocusChange",
            "editor.minimap.enabled": false,
            "workbench.colorTheme": "Default Dark+",
            "terminal.integrated.shell.linux": "/usr/bin/zsh"
          }
        dest: "{{ target_user_home }}/.config/Code/User/settings.json"
        mode: '0644'
      become: true
      become_user: "{{ username }}"
      tags: ide