---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true
  tags: core
  
- name: Install core packages
  apt:
    name: "{{ core_packages }}"
    state: present
  become: true
  tags: core

- name: Set .bashrc
  blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      alias d='docker'
      alias dc='docker compose'
      alias k='kubectl'
      export PATH=$PATH:/usr/local/go/bin
      export PATH=$PATH:/home/user/go/bin
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: yes
  become: false
  tags: core