---
- name: Обновление списка пакетов
  apt:
    update_cache: yes
  become: true
  tags: core
  
- name: Установка основных пакетов
  apt:
    name: "{{ core_packages }}"
    state: present
  become: true
  tags: core

- name: Установка DBeaver через Snap
  snap:
    name: dbeaver-ce
    classic: yes
    state: present
  become: true
  tags: core

- name: Добавление алиасов в .bashrc
  blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      alias d='docker'
      alias dc='docker compose'
      alias k='kubectl'
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ALIASES)"
    create: yes
  become: false
  tags: core