---
# Установка графических приложений

- name: Установка VS Code через Snap
  snap:
    name: code
    classic: yes
    state: present
  tags: desktop

- name: Установка DBeaver через Snap
  snap:
    name: dbeaver-ce
    classic: yes
    state: present
  tags: desktop