- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false
  become: true
  tags: dev

- name: Install Docker
  shell: wget -qO- https://get.docker.com | sh
  args:
    executable: /bin/bash
  changed_when: false
  become: true
  tags: dev

- name: Install VSCode, Postman and DBeaver
  snap:
    name: "{{ item }}"
    classic: yes
    state: present
  loop:
    - code
    - dbeaver-ce
    - postman
  become: true
  tags: dev
